---

# passwords below are created on the target machine with this python command
# python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")';

- user: name=s542530 password=$1$SomeSalt$.uq7zIpBXU/1emiCGdmEN/ state=present shell=/bin/bash
- user: name=s522102 password=$1$SomeSalt$k5CbpEkq9bEYMqRcsabg7. state=present shell=/bin/bash
- user: name=s532141 password=$1$SomeSalt$VF87AuQVnojrjU/m1RsvG/ state=present shell=/bin/bash
- user: name=s526720 password=$1$SomeSalt$hmN3sMNRgys2rfz8goCif0 state=present shell=/bin/bash
- user: name=s527765 password=$1$SomeSalt$/B0uW5BbaY/rGOp4J0l9U/ state=present shell=/bin/bash
- user: name=s443062 password=$1$SomeSalt$W5gEkKYj3/Sw1id2uCGrT. state=present shell=/bin/bash
- user: name=s549804 password=$1$SomeSalt$7Urf4kvnoF9bygnso1x/9/ state=present shell=/bin/bash
- user: name=s504421 password=$1$SomeSalt$Dcc2Xehw9n8GiKc.HbDqW0 state=present shell=/bin/bash
- user: name=s518315 password=$1$SomeSalt$6E6853gxFlIrAdVZywS6x. state=present shell=/bin/bash
- user: name=s542638 password=$1$SomeSalt$w0L/UJj6CsBldOIgAPowL. state=present shell=/bin/bash
- user: name=s523617 password=$1$SomeSalt$7wu./7n8pRU4GikxkWRe6/ state=present shell=/bin/bash
- user: name=s509146 password=$1$SomeSalt$yFjxR633XQNCul8COCXxs0 state=present shell=/bin/bash
- user: name=s529530 password=$1$SomeSalt$8zmN5OqgfR4jnJhye/tOG0 state=present shell=/bin/bash
- user: name=s449920 password=$1$SomeSalt$wLgn3V.r9qRNJgQ6XjFHb. state=present shell=/bin/bash
- user: name=s526566 password=$1$SomeSalt$IV.BPcINRSDFZRCeaJQ/D. state=present shell=/bin/bash
- user: name=s521142 password=$1$SomeSalt$vGLsdSnUPmaD538cFQjUv1 state=present shell=/bin/bash
- user: name=s508374 password=$1$SomeSalt$DlB1CANVZsPAcIfDJXBUw1 state=present shell=/bin/bash
- user: name=s517592 password=$1$SomeSalt$qYJLNAV3XdjCpdea8lMDG. state=present shell=/bin/bash
- user: name=s524246 password=$1$SomeSalt$lMCtfVP7dbHqnJRdtHH2g. state=present shell=/bin/bash
- user: name=s525138 password=$1$SomeSalt$8pq7TrmKwzWQb6ojKJiKd0 state=present shell=/bin/bash
- user: name=s516969 password=$1$SomeSalt$Jic45gw4d846Dze.nRcpD/ state=present shell=/bin/bash
- user: name=s499780 password=$1$SomeSalt$G12r7/Uo7PQ8uncmmI59z0 state=present shell=/bin/bash
- user: name=s535535 password=$1$SomeSalt$LPYY52495nZQuJfvbbjo71 state=present shell=/bin/bash
- user: name=s516002 password=$1$SomeSalt$toi8OmVKBrLC9ECJ1xZ6q1 state=present shell=/bin/bash
- user: name=s547829 password=$1$SomeSalt$JcaFKQjBIDuiYX9GLCdJQ1 state=present shell=/bin/bash
- user: name=s537702 password=$1$SomeSalt$UmSODL2uoL2grnTRcRAXR0 state=present shell=/bin/bash
- user: name=s533123 password=$1$SomeSalt$Q9kqOg2rAcSvSKaPQ80ma0 state=present shell=/bin/bash
- user: name=s549807 password=$1$SomeSalt$V0nlLUTVybFJbN52fYAQ.1 state=present shell=/bin/bash
- user: name=s523625 password=$1$SomeSalt$jUSxfEeVssyLVCClyr2qC1 state=present shell=/bin/bash
- user: name=s524292 password=$1$SomeSalt$XbvQ4K61TiQbSTii43LZi. state=present shell=/bin/bash
- user: name=s550349 password=$1$SomeSalt$BDB//Dkm0S0s5kw0imFYb. state=present shell=/bin/bash
- user: name=s491186 password=$1$SomeSalt$/h2ym8cyHg.olo7QIS0zm0 state=present shell=/bin/bash
- user: name=s520225 password=$1$SomeSalt$9s8yR1MmrcH9C5yPEUPWk1 state=present shell=/bin/bash
- user: name=s554911 password=$1$SomeSalt$NHVubSgEHJwKjeGDbZmZE1 state=present shell=/bin/bash
- user: name=s524681 password=$1$SomeSalt$HPuCHfZx9h0e3INqs87IL/ state=present shell=/bin/bash
- user: name=s542376 password=$1$SomeSalt$LV6CcQpugA71.b2XJQt0q/ state=present shell=/bin/bash
- user: name=s519491 password=$1$SomeSalt$7wQy42rW9hUQLfUIVNmxN/ state=present shell=/bin/bash
- user: name=s525148 password=$1$SomeSalt$jyTRBwhYOi7D9sxxVD6rM0 state=present shell=/bin/bash
- user: name=s523896 password=$1$SomeSalt$qbtEKoW2hOS6tDy.V1IzS1 state=present shell=/bin/bash
- user: name=s523701 password=$1$SomeSalt$vwhxxyIdY3B/zxOmulaWX0 state=present shell=/bin/bash
- user: name=s517143 password=$1$SomeSalt$FQnQ4g.2KbQu42HBCcCOX1 state=present shell=/bin/bash
- user: name=s504993 password=$1$SomeSalt$8SMaacV4mFNmEsLKB6alN/ state=present shell=/bin/bash
- user: name=s514414 password=$1$SomeSalt$3RCB5kqyjDCK1NgrtobMS0 state=present shell=/bin/bash
- user: name=s481009 password=$1$SomeSalt$g0NOJwUpKXHjWaBcrRov10 state=present shell=/bin/bash
- user: name=s510398 password=$1$SomeSalt$MMHRbEObbYY7E20ByR8FP0 state=present shell=/bin/bash
- user: name=s492724 password=$1$SomeSalt$76vqTSVfx66EYyNTNJL1r/ state=present shell=/bin/bash
- user: name=s509560 password=$1$SomeSalt$5wJ52m1T5qP3XMuJaHO1U0 state=present shell=/bin/bash
- user: name=s500555 password=$1$SomeSalt$if1WdDtHg/AcgKI6x2a7L1 state=present shell=/bin/bash
- user: name=s511097 password=$1$SomeSalt$gmuozmte3RBk8mdpwBy5c0 state=present shell=/bin/bash
- user: name=s510622 password=$1$SomeSalt$EIEk9zfoSVYEAkVjd8Ypy/ state=present shell=/bin/bash
- user: name=s503364 password=$1$SomeSalt$vQU9z5ltHri0mZWmhg7yq/ state=present shell=/bin/bash
- user: name=s458384 password=$1$SomeSalt$aZg5TMJ99F636BPzUR9/k. state=present shell=/bin/bash
- user: name=s511083 password=$1$SomeSalt$aQmx2pfnJU/vY94anTA131 state=present shell=/bin/bash
- user: name=s508175 password=$1$SomeSalt$Ngmsh3HD9Nfvd4DcHFuI4/ state=present shell=/bin/bash
- user: name=s488785 password=$1$SomeSalt$v9NJD5i4iHSC7OK72ftt3. state=present shell=/bin/bash
- user: name=s507388 password=$1$SomeSalt$bh/s7IXZ6cBAR8aQpKtpa/ state=present shell=/bin/bash
- user: name=s490046 password=$1$SomeSalt$mNbUNOdr1Za84PRxWrE5z. state=present shell=/bin/bash
- user: name=s494387 password=$1$SomeSalt$wuZuL6igTvYtEmSRkWvU8. state=present shell=/bin/bash
- user: name=s511109 password=$1$SomeSalt$0ZN0wwL/4ZLdexPKWkF/81 state=present shell=/bin/bash
- user: name=s513477 password=$1$SomeSalt$o9pOjZ.0BadnkCQxjmBmM0 state=present shell=/bin/bash
- user: name=s506961 password=$1$SomeSalt$1o73nSEJx8kqgSMrUXkAH/ state=present shell=/bin/bash
- user: name=s493497 password=$1$SomeSalt$Z2Zj2qApB3G3XXaelipmm1 state=present shell=/bin/bash
- user: name=s509043 password=$1$SomeSalt$MiTfQH0Wi05EjQrEvrgu0. state=present shell=/bin/bash
